apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-service-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-service-back
  template:
    metadata:
      labels:
        app: voting-service-back
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: voting-service-back
        image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 6379
          name: redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-service-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-service-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: voting-service-front
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: voting-service-front
        image: ghcr.io/james-leha/demoday-aks-to-z:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "voting-service-back"
