apiVersion: v1
kind: Service
metadata:
  name: voting-service-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: voting-service-front
---
apiVersion: v1
kind: Service
metadata:
  name: voting-service-back
spec:
  ports:
  - port: 6379
  selector:
    app: voting-service-back